services:
  database:
    container_name: pizzadev_db
    image: postgres:17.5
    environment:
      POSTGRES_USER: ${ENV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ENV_POSTGRES_PASSWORD}
      POSTGRES_DB: pizzadev
    volumes:
      - pizzadev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pizzadev_data: